// Generated by scripts/gen-lab-fixtures.mjs from src/test/fixtures/
// (pinned in its VERSION); never edited by hand. Run
// scripts/sync-fixtures.sh to move a pin.

/**
 * The uspace-lab commit the common examples were copied at.
 *
 * @public
 */
export const LAB_COMMIT = "18d6f321a12f897f96e24ef842f4ce9d5a6bde33";

/** Every vendored example, by its path under src/test/fixtures/. */
export const LAB_EXAMPLES: Readonly<Record<string, unknown>> = {
  "ansp/track/manned/v1/live-ads-b.json": {
    "schema": "track/manned/v1",
    "msg_id": "01K6N5SXS5AA819X9YP981068V",
    "producer": "ansp/manned-feed",
    "ts": "2026-10-02T12:00:00.000Z",
    "rx_ts": "2026-10-02T12:00:00.180Z",
    "captured_at": "2026-10-02T12:00:00.000Z",
    "time_source": "receiver",
    "backlog": false,
    "body": {
      "icao24": "4ca7b5",
      "callsign": "TST123",
      "position": {
        "lat": 41.721,
        "lng": 44.793
      },
      "alt_pressure_m": 1524,
      "alt_wgs84_m": 1561,
      "gs_ms": 72.5,
      "track_deg": 134,
      "vrate_ms": -2.5,
      "emergency": false,
      "squawk": "4521",
      "source_class": "ads_b",
      "quality": {
        "nic": 8,
        "nacp": 9
      },
      "trust": "surveillance",
      "source": "ansp_feed",
      "source_instance": "adsb-tbs",
      "state": "live",
      "relevant": true,
      "policy_version": "1"
    }
  },
  "ansp/track/manned/v1/source-disabled-pressure-only.json": {
    "schema": "track/manned/v1",
    "msg_id": "01K6N5SXS5AA819X9YP981068X",
    "producer": "ansp/manned-feed",
    "ts": null,
    "rx_ts": "2026-10-02T12:00:00.180Z",
    "captured_at": "2026-10-02T12:00:00.000Z",
    "time_source": "receiver",
    "backlog": false,
    "body": {
      "icao24": "4ca7b5",
      "callsign": null,
      "position": {
        "lat": 41.721,
        "lng": 44.793
      },
      "alt_pressure_m": 1524,
      "alt_wgs84_m": null,
      "gs_ms": null,
      "track_deg": null,
      "vrate_ms": null,
      "emergency": null,
      "squawk": null,
      "source_class": "ads_b",
      "quality": {
        "nic": 8,
        "nacp": 9
      },
      "trust": "surveillance",
      "source": "ansp_feed",
      "source_instance": "adsb-tbs",
      "state": "source_disabled",
      "relevant": true,
      "policy_version": "1"
    }
  },
  "ansp/track/manned/v1/stale-after-silence.json": {
    "schema": "track/manned/v1",
    "msg_id": "01K6N5SXS5AA819X9YP981068W",
    "producer": "ansp/manned-feed",
    "ts": "2026-10-02T12:00:00.000Z",
    "rx_ts": "2026-10-02T12:00:16.000Z",
    "captured_at": "2026-10-02T12:00:00.000Z",
    "time_source": "receiver",
    "backlog": false,
    "body": {
      "icao24": "4ca7b5",
      "callsign": "TST123",
      "position": {
        "lat": 41.721,
        "lng": 44.793
      },
      "alt_pressure_m": 1524,
      "alt_wgs84_m": 1561,
      "gs_ms": 72.5,
      "track_deg": 134,
      "vrate_ms": -2.5,
      "emergency": false,
      "squawk": "4521",
      "source_class": "ads_b",
      "quality": {
        "nic": 8,
        "nacp": 9
      },
      "trust": "surveillance",
      "source": "ansp_feed",
      "source_instance": "adsb-tbs",
      "state": "stale",
      "relevant": true,
      "policy_version": "1"
    }
  },
  "lab/console/snapshot/v1/authority-picture.json": {
    "schema": "console/snapshot/v1",
    "msg_id": "01K6W6VZSKDENC8SP3804GVA35",
    "producer": "authority/picture-ws",
    "ts": "2026-10-02T09:15:06.100Z",
    "rx_ts": "2026-10-02T09:15:06.100Z",
    "captured_at": "2026-10-02T09:15:06.100Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "tracks": [
        {
          "schema": "track/telemetry/v1",
          "msg_id": "01K6M9S346Q3D25VT4F5V37E3S",
          "producer": "ussp-1/telemetry-ingest-1",
          "ts": "2026-10-02T09:15:03.120Z",
          "rx_ts": "2026-10-02T09:15:03.245Z",
          "captured_at": "2026-10-02T09:15:03.214Z",
          "time_source": "source_clock",
          "backlog": false,
          "body": {
            "track_id": "ussp-1:FL-2026-000417",
            "trust": "authenticated",
            "source": "operator_ws",
            "source_instance": "op-client-0042",
            "position": {
              "lat": 41.7151,
              "lng": 44.8271
            },
            "alt_wgs84_m": 594.3,
            "alt_amsl_m": 565.1,
            "alt_source": "geodetic",
            "alt_pressure_m": null,
            "height_m": 82,
            "height_ref": "TakeoffLocation",
            "speed_ms": 7.4,
            "track_deg": 128,
            "vspeed_ms": 0.3,
            "accuracy_h_m": 3,
            "accuracy_v_m": 4.5,
            "status": "Airborne",
            "emergency": false,
            "identification": {
              "status": "registered",
              "reason": "session_binding",
              "serial": "1596A7B2C3D4E5F6G7H8",
              "operator_reg": "GEOrx8mtw5ivq3pd",
              "registered_operator_reg": null,
              "mismatch": false,
              "registry_uas_id": "uas-000731",
              "basis": "authenticated"
            },
            "flight_id": "FL-2026-000417",
            "intent_id": "8c1f3f2e-7d0e-4a8b-9a51-0e4b7d6f2c11",
            "cell": "c5:1317:2248"
          }
        },
        {
          "schema": "track/telemetry/v1",
          "msg_id": "01K63E28JT97KB6CQ643DZVMXX",
          "producer": "authority-1/rid-ingest-2",
          "ts": "2026-10-02T09:15:04.000Z",
          "rx_ts": "2026-10-02T09:15:04.410Z",
          "captured_at": "2026-10-02T09:15:04.000Z",
          "time_source": "broadcast",
          "backlog": false,
          "body": {
            "track_id": "authority-1:rid:4A:7C:91:0E:22:B5",
            "trust": "broadcast",
            "source": "direct_rid",
            "source_instance": "rx-kut-03",
            "position": {
              "lat": 42.2679,
              "lng": 42.6946
            },
            "alt_wgs84_m": null,
            "alt_amsl_m": null,
            "alt_source": "pressure",
            "alt_pressure_m": 241.5,
            "height_m": null,
            "height_ref": null,
            "speed_ms": 11.25,
            "track_deg": 0,
            "vspeed_ms": null,
            "accuracy_h_m": 10,
            "accuracy_v_m": null,
            "status": "Airborne",
            "emergency": false,
            "identification": {
              "status": "unknown_operator",
              "reason": "operator_absent",
              "serial": "1581F5FJD239C00DW1B5",
              "operator_reg": null,
              "registered_operator_reg": null,
              "mismatch": false,
              "basis": "as_broadcast"
            },
            "flight_id": null,
            "intent_id": null,
            "cell": "c5:1322:2226"
          }
        }
      ],
      "alerts": [
        {
          "schema": "violation/v1",
          "msg_id": "01K6H3BV4H15G5E4G7X0NTH82F",
          "producer": "authority/detect",
          "ts": "2026-10-02T09:15:04.000Z",
          "rx_ts": "2026-10-02T09:15:04.500Z",
          "captured_at": "2026-10-02T09:15:04.000Z",
          "time_source": "system",
          "backlog": false,
          "body": {
            "violation_id": "v-2026-00031",
            "kind": "height_120m"
          }
        }
      ],
      "manned": [
        {
          "schema": "track/manned/v1",
          "msg_id": "01K67AG3BCKKDJWBHP1G201CYF",
          "producer": "ansp/manned-feed",
          "ts": "2026-10-02T09:15:05.000Z",
          "rx_ts": "2026-10-02T09:15:05.100Z",
          "captured_at": "2026-10-02T09:15:05.000Z",
          "time_source": "source_clock",
          "backlog": false,
          "body": {
            "icao24": "4ca7b5",
            "callsign": "TGZ123"
          }
        }
      ],
      "zones_version": "zones-2026-10-02-0007"
    }
  },
  "lab/console/snapshot/v1/empty-before-first-cis-version.json": {
    "schema": "console/snapshot/v1",
    "msg_id": "01K6NR5YHCF05G59S2S1KKE59R",
    "producer": "cisp/api",
    "ts": "2026-10-02T09:15:06.100Z",
    "rx_ts": "2026-10-02T09:15:06.100Z",
    "captured_at": "2026-10-02T09:15:06.100Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "tracks": [],
      "alerts": [],
      "manned": [],
      "zones_version": null
    }
  },
  "lab/console/snapshot/v1/ussp-traffic.json": {
    "schema": "console/snapshot/v1",
    "msg_id": "01K6RJFJ2XBAHW0GQNMF2KDPB0",
    "producer": "ussp/traffic-ws",
    "ts": "2026-10-02T09:15:06.100Z",
    "rx_ts": "2026-10-02T09:15:06.100Z",
    "captured_at": "2026-10-02T09:15:06.100Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "tracks": [
        {
          "schema": "track/telemetry/v1",
          "msg_id": "01K6M9S346Q3D25VT4F5V37E3S",
          "producer": "ussp-1/telemetry-ingest-1",
          "ts": "2026-10-02T09:15:03.120Z",
          "rx_ts": "2026-10-02T09:15:03.245Z",
          "captured_at": "2026-10-02T09:15:03.214Z",
          "time_source": "source_clock",
          "backlog": false,
          "body": {
            "track_id": "ussp-1:FL-2026-000417",
            "trust": "authenticated",
            "source": "operator_ws",
            "source_instance": "op-client-0042",
            "position": {
              "lat": 41.7151,
              "lng": 44.8271
            },
            "alt_wgs84_m": 594.3,
            "alt_amsl_m": 565.1,
            "alt_source": "geodetic",
            "alt_pressure_m": null,
            "height_m": 82,
            "height_ref": "TakeoffLocation",
            "speed_ms": 7.4,
            "track_deg": 128,
            "vspeed_ms": 0.3,
            "accuracy_h_m": 3,
            "accuracy_v_m": 4.5,
            "status": "Airborne",
            "emergency": false,
            "identification": {
              "status": "registered",
              "reason": "session_binding",
              "serial": "1596A7B2C3D4E5F6G7H8",
              "operator_reg": "GEOrx8mtw5ivq3pd",
              "registered_operator_reg": null,
              "mismatch": false,
              "registry_uas_id": "uas-000731",
              "basis": "authenticated"
            },
            "flight_id": "FL-2026-000417",
            "intent_id": "8c1f3f2e-7d0e-4a8b-9a51-0e4b7d6f2c11",
            "cell": "c5:1317:2248"
          }
        }
      ],
      "alerts": [
        {
          "schema": "alert/v1",
          "msg_id": "01K61RNJ47E65GH2BH8VGS9ZM5",
          "producer": "ussp/monitor",
          "ts": "2026-10-02T09:15:03.214Z",
          "rx_ts": "2026-10-02T09:15:03.300Z",
          "captured_at": "2026-10-02T09:15:03.214Z",
          "time_source": "system",
          "backlog": false,
          "body": {
            "alert_id": "al-000912",
            "kind": "proximity",
            "severity": "warning",
            "state": "raised"
          }
        }
      ],
      "manned": [],
      "zones_version": "zones-2026-10-02-0007"
    }
  },
  "lab/console/status/v1/ansp-feed-disabled-source.json": {
    "schema": "console/status/v1",
    "msg_id": "01K68XE6SZAEAVSNTCPM5Q1NXW",
    "producer": "ansp/manned-feed",
    "ts": "2026-10-02T09:15:06.000Z",
    "rx_ts": "2026-10-02T09:15:06.000Z",
    "captured_at": "2026-10-02T09:15:06.000Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "connection_id": "m-44",
      "server_ts": "2026-10-02T09:15:06.000Z",
      "policy_version": "3",
      "stale_after_s": 10,
      "live_max_age_s": 4,
      "dropped_frames": 0,
      "degraded": [
        "source_disabled"
      ],
      "sources": [
        {
          "source": "ansp_feed",
          "source_instance": "adsb-tbs",
          "state": "disabled",
          "since": "2026-10-02T09:00:00.000Z",
          "age_s": 906,
          "disabled_by": "type",
          "disabled_by_who": "supervisor:g.kapanadze",
          "counters": {
            "accepted": 99812,
            "refused": 0
          }
        }
      ]
    }
  },
  "lab/console/status/v1/authority-picture.json": {
    "schema": "console/status/v1",
    "msg_id": "01K6B9Y73MY63FCH26W14WMCHW",
    "producer": "authority/picture-ws",
    "ts": "2026-10-02T09:15:06.000Z",
    "rx_ts": "2026-10-02T09:15:06.000Z",
    "captured_at": "2026-10-02T09:15:06.000Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "connection_id": "c-7f3a91",
      "server_ts": "2026-10-02T09:15:06.000Z",
      "policy_version": "demo-2026-10-01",
      "stale_after_s": 5,
      "live_max_age_s": 2,
      "dropped_frames": 0,
      "degraded": [],
      "sources": [
        {
          "source": "direct_rid",
          "source_instance": "rx-tbs-01",
          "state": "live",
          "since": "2026-10-02T06:00:12.000Z",
          "age_s": 0.4,
          "disabled_by": null,
          "counters": {
            "accepted": 182344,
            "refused": 12,
            "dropped_backlog": 0
          }
        },
        {
          "source": "network_rid",
          "source_instance": "ussp-peer-ge-02",
          "state": "disabled",
          "since": "2026-10-02T08:41:00.517Z",
          "age_s": 2054.1,
          "disabled_by": "instance",
          "disabled_by_who": "admin:n.beridze",
          "counters": {
            "accepted": 5521,
            "refused": 340
          }
        }
      ],
      "projection_age_s": 1.2,
      "cis_age_s": 14,
      "nats": "connected",
      "dp_state": "polling"
    }
  },
  "lab/console/status/v1/cisp-resync.json": {
    "schema": "console/status/v1",
    "msg_id": "01K6YFGCW8T7SWM4FV4DK79Q9G",
    "producer": "cisp-1/api-2",
    "ts": "2026-10-02T09:15:06.000Z",
    "rx_ts": "2026-10-02T09:15:06.000Z",
    "captured_at": "2026-10-02T09:15:06.000Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "connection_id": "c-0b21e4",
      "server_ts": "2026-10-02T09:15:06.000Z",
      "policy_version": "1",
      "stale_after_s": 60,
      "live_max_age_s": 15,
      "dropped_frames": 3,
      "degraded": [
        "publisher_stale"
      ],
      "sources": [],
      "datasets": {
        "zones": {
          "version": "zones-2026-10-02-0007",
          "age_s": 812.5
        },
        "uspace_airspace": {
          "version": "uspace-2026-09-30-0002",
          "age_s": 160233
        }
      },
      "cis_version": "zones-2026-10-02-0007",
      "resync_since": "2026-10-02T09:10:00.000Z"
    }
  },
  "lab/envelope/v1/cis-change-frame.json": {
    "schema": "cis/change/v1",
    "msg_id": "01K6WPQ5E6EYCNDY0YP57RCYBV",
    "producer": "cisp/api",
    "ts": "2026-10-02T09:15:03.120Z",
    "rx_ts": "2026-10-02T09:15:03.245Z",
    "captured_at": "2026-10-02T09:15:03.214Z",
    "time_source": "source_clock",
    "backlog": false,
    "body": {
      "dataset": "zones",
      "version": "zones-2026-10-02-0007"
    }
  },
  "lab/envelope/v1/lab-backlog-frame.json": {
    "schema": "coordination/annex_v/v1",
    "msg_id": "01K6CD1GDJFMGT83PXT891WB09",
    "producer": "lab/sim-ussp",
    "ts": "2026-10-02T09:15:05.500Z",
    "rx_ts": "2026-10-02T09:15:05.612Z",
    "captured_at": "2026-10-02T09:15:05.580Z",
    "time_source": "provider",
    "backlog": true,
    "body": {}
  },
  "lab/envelope/v1/manned-frame-without-source-clock.json": {
    "schema": "track/manned/v1",
    "msg_id": "01K6N5SXS5AA819X9YP981068V",
    "producer": "ansp-1/manned-feed-1",
    "ts": null,
    "rx_ts": "2026-10-02T09:15:04.410Z",
    "captured_at": "2026-10-02T09:15:04.000Z",
    "time_source": "receiver",
    "backlog": false,
    "body": {
      "icao24": "4ca7b5"
    }
  },
  "lab/source/status/v1/disabled-by-instance.json": {
    "schema": "source/status/v1",
    "msg_id": "01K6DJ8FSSZ5AWSH8VHTPRE95B",
    "producer": "authority-1/api-1",
    "ts": "2026-10-02T09:15:06.002Z",
    "rx_ts": "2026-10-02T09:15:06.002Z",
    "captured_at": "2026-10-02T09:15:06.002Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "source": "network_rid",
      "source_instance": "ussp-peer-ge-02",
      "state": "disabled",
      "since": "2026-10-02T08:41:00.517Z",
      "age_s": 2054.1,
      "disabled_by": "instance",
      "disabled_by_who": "admin:n.beridze",
      "counters": {
        "accepted": 5521,
        "refused": 340
      }
    }
  },
  "lab/source/status/v1/live-receiver.json": {
    "schema": "source/status/v1",
    "msg_id": "01K6NPZX45HY43KWJRP1XPA7Z3",
    "producer": "authority/rid-ingest",
    "ts": "2026-10-02T09:15:06.000Z",
    "rx_ts": "2026-10-02T09:15:06.000Z",
    "captured_at": "2026-10-02T09:15:06.000Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "source": "direct_rid",
      "source_instance": "rx-tbs-01",
      "state": "live",
      "since": "2026-10-02T06:00:12.000Z",
      "age_s": 0.4,
      "disabled_by": null,
      "counters": {
        "accepted": 182344,
        "refused": 12,
        "dropped_backlog": 0
      }
    }
  },
  "lab/source/status/v1/never-heard-type.json": {
    "schema": "source/status/v1",
    "msg_id": "01K69EE0ZBGJ09TQM83XSSSS6Y",
    "producer": "ussp/traffic-ws",
    "ts": "2026-10-02T09:15:06.010Z",
    "rx_ts": "2026-10-02T09:15:06.010Z",
    "captured_at": "2026-10-02T09:15:06.010Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "source": "adsb_rx",
      "source_instance": null,
      "state": "unknown",
      "since": "2026-10-02T09:14:58.000Z",
      "age_s": null,
      "disabled_by": null,
      "counters": {
        "accepted": 0,
        "refused": 0
      }
    }
  },
  "lab/track/telemetry/v1/authenticated-operator-session.json": {
    "schema": "track/telemetry/v1",
    "msg_id": "01K6M9S346Q3D25VT4F5V37E3S",
    "producer": "ussp-1/telemetry-ingest-1",
    "ts": "2026-10-02T09:15:03.120Z",
    "rx_ts": "2026-10-02T09:15:03.245Z",
    "captured_at": "2026-10-02T09:15:03.214Z",
    "time_source": "source_clock",
    "backlog": false,
    "body": {
      "track_id": "ussp-1:FL-2026-000417",
      "trust": "authenticated",
      "source": "operator_ws",
      "source_instance": "op-client-0042",
      "position": {
        "lat": 41.7151,
        "lng": 44.8271
      },
      "alt_wgs84_m": 594.3,
      "alt_amsl_m": 565.1,
      "alt_source": "geodetic",
      "alt_pressure_m": null,
      "height_m": 82,
      "height_ref": "TakeoffLocation",
      "speed_ms": 7.4,
      "track_deg": 128,
      "vspeed_ms": 0.3,
      "accuracy_h_m": 3,
      "accuracy_v_m": 4.5,
      "status": "Airborne",
      "emergency": false,
      "identification": {
        "status": "registered",
        "reason": "session_binding",
        "serial": "1596A7B2C3D4E5F6G7H8",
        "operator_reg": "GEOrx8mtw5ivq3pd",
        "registered_operator_reg": null,
        "mismatch": false,
        "registry_uas_id": "uas-000731",
        "basis": "authenticated"
      },
      "flight_id": "FL-2026-000417",
      "intent_id": "8c1f3f2e-7d0e-4a8b-9a51-0e4b7d6f2c11",
      "cell": "c5:1317:2248"
    }
  },
  "lab/track/telemetry/v1/direct-rid-pressure-altitude.json": {
    "schema": "track/telemetry/v1",
    "msg_id": "01K63E28JT97KB6CQ643DZVMXX",
    "producer": "authority-1/rid-ingest-2",
    "ts": "2026-10-02T09:15:04.000Z",
    "rx_ts": "2026-10-02T09:15:04.410Z",
    "captured_at": "2026-10-02T09:15:04.000Z",
    "time_source": "broadcast",
    "backlog": false,
    "body": {
      "track_id": "authority-1:rid:4A:7C:91:0E:22:B5",
      "trust": "broadcast",
      "source": "direct_rid",
      "source_instance": "rx-kut-03",
      "position": {
        "lat": 42.2679,
        "lng": 42.6946
      },
      "alt_wgs84_m": null,
      "alt_amsl_m": null,
      "alt_source": "pressure",
      "alt_pressure_m": 241.5,
      "height_m": null,
      "height_ref": null,
      "speed_ms": 11.25,
      "track_deg": 0,
      "vspeed_ms": null,
      "accuracy_h_m": 10,
      "accuracy_v_m": null,
      "status": "Airborne",
      "emergency": false,
      "identification": {
        "status": "unknown_operator",
        "reason": "operator_absent",
        "serial": "1581F5FJD239C00DW1B5",
        "operator_reg": null,
        "registered_operator_reg": null,
        "mismatch": false,
        "basis": "as_broadcast"
      },
      "flight_id": null,
      "intent_id": null,
      "cell": "c5:1322:2226"
    }
  },
  "lab/track/telemetry/v1/serial-conflict-backlog.json": {
    "schema": "track/telemetry/v1",
    "msg_id": "01K6QKFBF5KZNWJ47TAN9ZT24M",
    "producer": "authority/detect",
    "rx_ts": "2026-10-02T09:16:10.002Z",
    "captured_at": "2026-10-02T09:16:10.002Z",
    "time_source": "system",
    "backlog": true,
    "body": {
      "track_id": "authority:rid:1581F5FJD239C00DW1B5",
      "trust": "broadcast",
      "source": "direct_rid",
      "source_instance": "rx-tbs-01",
      "position": {
        "lat": 41.7302,
        "lng": 44.7905
      },
      "alt_wgs84_m": 612,
      "alt_amsl_m": 583.4,
      "alt_source": "geodetic",
      "alt_pressure_m": null,
      "height_m": 95,
      "height_ref": "GroundLevel",
      "speed_ms": null,
      "track_deg": null,
      "vspeed_ms": null,
      "accuracy_h_m": null,
      "accuracy_v_m": null,
      "status": null,
      "emergency": false,
      "identification": {
        "status": "registered",
        "reason": "serial_conflict",
        "serial": "1581F5FJD239C00DW1B5",
        "operator_reg": "GEOrx8mtw5ivq3pd",
        "registered_operator_reg": "GEO7kq2mzt3hpa1c",
        "mismatch": true,
        "registry_uas_id": null,
        "basis": "as_broadcast"
      },
      "flight_id": null,
      "intent_id": null
    }
  },
  "lab/zone/applicable/v1/cis-applicability-unknown.json": {
    "schema": "zone/applicable/v1",
    "msg_id": "01K65GQAPENECFSECZP11HYGCP",
    "producer": "ussp/api",
    "ts": "2026-10-02T09:15:00.000Z",
    "rx_ts": "2026-10-02T09:15:00.000Z",
    "captured_at": "2026-10-02T09:15:00.000Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "identifier": "DAR0A1F",
      "type": "CONDITIONAL",
      "applies": true,
      "cis_applicability": "unknown",
      "version": "12",
      "valid_from": "2026-10-02T08:00:00.000Z",
      "valid_to": "2026-10-02T12:00:00.000Z",
      "at": "2026-10-02T09:15:00.000Z",
      "cis_version": "zones-2026-10-02-0007"
    }
  },
  "lab/zone/applicable/v1/permanent-zone-not-applicable.json": {
    "schema": "zone/applicable/v1",
    "msg_id": "01K6QY77ZXYYK596NGYA1DQ91K",
    "producer": "authority/detect",
    "ts": "2026-10-02T09:15:00.000Z",
    "rx_ts": "2026-10-02T09:15:00.000Z",
    "captured_at": "2026-10-02T09:15:00.000Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "identifier": "GE-R12",
      "type": "REQ_AUTHORIZATION",
      "applies": false,
      "cis_applicability": "not_applicable",
      "version": "3",
      "valid_from": null,
      "valid_to": null
    }
  },
  "lab/zone/applicable/v1/prohibited-restriction-applies.json": {
    "schema": "zone/applicable/v1",
    "msg_id": "01K6S3C4DWA7N36096Q14DR9GP",
    "producer": "ussp/api",
    "ts": "2026-10-02T09:15:00.000Z",
    "rx_ts": "2026-10-02T09:15:00.000Z",
    "captured_at": "2026-10-02T09:15:00.000Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "identifier": "DAR0A1F",
      "type": "PROHIBITED",
      "applies": true,
      "cis_applicability": "applies",
      "version": "12",
      "valid_from": "2026-10-02T08:00:00.000Z",
      "valid_to": "2026-10-02T12:00:00.000Z",
      "at": "2026-10-02T09:15:00.000Z",
      "cis_version": "zones-2026-10-02-0007"
    }
  },
  "ussp/alert/v1/nonconformance-raised.json": {
    "schema": "alert/v1",
    "msg_id": "01K6Q2A3B4C5D6E7F8G9H0J1K2",
    "producer": "ussp/monitor",
    "ts": "2026-10-03T12:00:05.000Z",
    "rx_ts": "2026-10-03T12:00:05.000Z",
    "captured_at": "2026-10-03T12:00:05.000Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "alert_id": "0b6f0f7e-8d7c-4c1a-9e2b-3a4b5c6d7e8f",
      "kind": "nonconformance",
      "severity": "critical",
      "state": "raised",
      "clear_reason": null,
      "flight_id": "11111111-1111-4111-8111-111111111111",
      "intent_id": "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      "authorisation_number": "USSP-DEV-20261003-0001",
      "captured_at": "2026-10-03T12:00:04.812345678Z",
      "raised_at": "2026-10-03T12:00:04.812345678Z",
      "updated_at": "2026-10-03T12:00:04.812345678Z",
      "policy_version": 3,
      "detail": {
        "reason": "threshold_exceeded",
        "distance_outside_m": 61.5,
        "height_over_m": 0,
        "time_outside_s": 0,
        "within_threshold": false
      }
    }
  },
  "ussp/alert/v1/proximity-cleared-resolved.json": {
    "schema": "alert/v1",
    "msg_id": "01K6Q2A3B4C5D6E7F8G9H0J1K2",
    "producer": "ussp/monitor",
    "ts": "2026-10-03T12:00:05.000Z",
    "rx_ts": "2026-10-03T12:00:05.000Z",
    "captured_at": "2026-10-03T12:00:05.000Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "alert_id": "5f0c2a8e-3b1d-4c6e-9a7f-1d2e3f4a5b6c",
      "kind": "proximity",
      "severity": "critical",
      "state": "cleared",
      "clear_reason": "resolved",
      "flight_id": "11111111-1111-4111-8111-111111111111",
      "intent_id": "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      "authorisation_number": "USSP-DEV-20261003-0001",
      "captured_at": "2026-10-03T12:00:04.812Z",
      "raised_at": "2026-10-03T12:00:04.812Z",
      "updated_at": "2026-10-03T12:00:38.000Z",
      "policy_version": 3,
      "detail": {
        "t_cpa_s": 0,
        "d_cpa_h_m": 58.1,
        "d_alt_m": 0,
        "d_horizontal_now_m": 58.1,
        "vertical_separation_known": true,
        "los_start_s": 0,
        "peer": {
          "track_id": "22222222-2222-4222-8222-222222222222",
          "trust": "authenticated",
          "source": "operator_ws"
        },
        "pair_id": "3f2a9c1b7e5d4a3b2c1d0e9f",
        "evaluation_period_s": 1
      },
      "clearing_detail": {
        "clearing_at": "2026-10-03T12:00:37.812Z",
        "clearing_d_horizontal_now_m": 64,
        "clearing_d_alt_now_m": 0,
        "clearing_t_cpa_s": 0,
        "clearing_d_cpa_horizontal_m": 64,
        "clearing_d_alt_at_cpa_m": 0,
        "clearing_vertical_separation_known": true
      }
    }
  },
  "ussp/alert/v1/proximity-e-conspicuity-broadcast-peer.json": {
    "schema": "alert/v1",
    "msg_id": "01K6Q2A3B4C5D6E7F8G9H0J1K2",
    "producer": "ussp/monitor",
    "ts": "2026-10-03T12:00:05.000Z",
    "rx_ts": "2026-10-03T12:00:05.000Z",
    "captured_at": "2026-10-03T12:00:05.000Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "alert_id": "5f0c2a8e-3b1d-4c6e-9a7f-1d2e3f4a5b6c",
      "kind": "proximity",
      "severity": "critical",
      "state": "raised",
      "clear_reason": null,
      "flight_id": "11111111-1111-4111-8111-111111111111",
      "intent_id": "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      "authorisation_number": "USSP-DEV-20261003-0001",
      "captured_at": "2026-10-03T12:00:04.812Z",
      "raised_at": "2026-10-03T12:00:04.812Z",
      "updated_at": "2026-10-03T12:00:05.000Z",
      "policy_version": 3,
      "detail": {
        "t_cpa_s": 29.4,
        "d_cpa_h_m": 0.4,
        "d_alt_m": 0,
        "d_horizontal_now_m": 588,
        "vertical_separation_known": true,
        "los_start_s": 26.4,
        "peer": {
          "track_id": "4ca7b6",
          "trust": "broadcast",
          "source": "adsb_rx"
        },
        "pair_id": "3f2a9c1b7e5d4a3b2c1d0e9f",
        "evaluation_period_s": 1
      }
    }
  },
  "ussp/alert/v1/proximity-manned-pressure-altitude-escalated.json": {
    "schema": "alert/v1",
    "msg_id": "01K6Q2A3B4C5D6E7F8G9H0J1K2",
    "producer": "ussp/monitor",
    "ts": "2026-10-03T12:00:05.000Z",
    "rx_ts": "2026-10-03T12:00:05.000Z",
    "captured_at": "2026-10-03T12:00:05.000Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "alert_id": "5f0c2a8e-3b1d-4c6e-9a7f-1d2e3f4a5b6c",
      "kind": "proximity",
      "severity": "critical",
      "state": "updated",
      "clear_reason": null,
      "flight_id": "11111111-1111-4111-8111-111111111111",
      "intent_id": "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      "authorisation_number": "USSP-DEV-20261003-0001",
      "captured_at": "2026-10-03T12:00:04.812Z",
      "raised_at": "2026-10-03T12:00:04.812Z",
      "updated_at": "2026-10-03T12:00:05.000Z",
      "policy_version": 3,
      "detail": {
        "t_cpa_s": 29.4,
        "d_cpa_h_m": 0.4,
        "d_alt_m": null,
        "d_horizontal_now_m": 588,
        "vertical_separation_known": false,
        "los_start_s": 26.4,
        "peer": {
          "track_id": "4ca7b5",
          "trust": "surveillance",
          "source": "ansp_feed"
        },
        "pair_id": "3f2a9c1b7e5d4a3b2c1d0e9f",
        "evaluation_period_s": 2
      },
      "acked_at": null,
      "escalated_at": "2026-10-03T12:00:35.120Z"
    }
  },
  "ussp/alert/v1/proximity-raised-head-on.json": {
    "schema": "alert/v1",
    "msg_id": "01K6Q2A3B4C5D6E7F8G9H0J1K2",
    "producer": "ussp/monitor",
    "ts": "2026-10-03T12:00:05.000Z",
    "rx_ts": "2026-10-03T12:00:05.000Z",
    "captured_at": "2026-10-03T12:00:05.000Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "alert_id": "5f0c2a8e-3b1d-4c6e-9a7f-1d2e3f4a5b6c",
      "kind": "proximity",
      "severity": "critical",
      "state": "raised",
      "clear_reason": null,
      "flight_id": "11111111-1111-4111-8111-111111111111",
      "intent_id": "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      "authorisation_number": "USSP-DEV-20261003-0001",
      "captured_at": "2026-10-03T12:00:04.812Z",
      "raised_at": "2026-10-03T12:00:04.812Z",
      "updated_at": "2026-10-03T12:00:05.000Z",
      "policy_version": 3,
      "detail": {
        "t_cpa_s": 29.4,
        "d_cpa_h_m": 0.4,
        "d_alt_m": 0,
        "d_horizontal_now_m": 588,
        "vertical_separation_known": true,
        "los_start_s": 26.4,
        "peer": {
          "track_id": "22222222-2222-4222-8222-222222222222",
          "trust": "authenticated",
          "source": "operator_ws"
        },
        "pair_id": "3f2a9c1b7e5d4a3b2c1d0e9f",
        "evaluation_period_s": 1
      }
    }
  },
  "ussp/alert/v1/restriction-activated-withdrawn.json": {
    "schema": "alert/v1",
    "msg_id": "01K6Q2A3B4C5D6E7F8G9H0J1K2",
    "producer": "ussp/api",
    "ts": "2026-10-03T12:00:05.000Z",
    "rx_ts": "2026-10-03T12:00:05.000Z",
    "captured_at": "2026-10-03T12:00:05.000Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "alert_id": "4d6f0f7e-8d7c-4c1a-9e2b-3a4b5c6d7e82",
      "kind": "restriction_activated",
      "severity": "critical",
      "state": "raised",
      "clear_reason": null,
      "flight_id": null,
      "intent_id": "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      "authorisation_number": "USSP-DEV-20261003-0001",
      "captured_at": "2026-10-03T12:00:04.812345678Z",
      "raised_at": "2026-10-03T12:00:04.812345678Z",
      "updated_at": "2026-10-03T12:00:04.812345678Z",
      "policy_version": 3,
      "detail": {
        "cause": "restriction",
        "ref": "TRS001",
        "restriction_id": "TRS001",
        "reason": "restriction_active",
        "decision": "withdrawn",
        "withdrawn": true,
        "authorisation_updated": false,
        "previous_state": "accepted",
        "intent_state": "withdrawn",
        "affected_intents": [
          "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"
        ],
        "window": {
          "starts_at": "2026-10-03T12:00:00Z",
          "ends_at": "2026-10-03T14:00:00Z"
        },
        "change_reason": "restriction TRS001",
        "cis_version": "zones:4,uspace_airspace:2,restrictions:9"
      }
    }
  },
  "ussp/alert/v1/zone-incursion-agl-not-judged.json": {
    "schema": "alert/v1",
    "msg_id": "01K6Q2A3B4C5D6E7F8G9H0J1K2",
    "producer": "ussp/monitor",
    "ts": "2026-10-03T12:00:05.000Z",
    "rx_ts": "2026-10-03T12:00:05.000Z",
    "captured_at": "2026-10-03T12:00:05.000Z",
    "time_source": "system",
    "backlog": false,
    "body": {
      "alert_id": "3c6f0f7e-8d7c-4c1a-9e2b-3a4b5c6d7e81",
      "kind": "zone_incursion",
      "severity": "warning",
      "state": "raised",
      "clear_reason": null,
      "flight_id": "11111111-1111-4111-8111-111111111111",
      "intent_id": "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      "authorisation_number": "USSP-DEV-20261003-0001",
      "captured_at": "2026-10-03T12:00:04.812345678Z",
      "raised_at": "2026-10-03T12:00:04.812345678Z",
      "updated_at": "2026-10-03T12:00:04.900000000Z",
      "policy_version": 3,
      "detail": {
        "identifier": "TZP001",
        "restriction": "PROHIBITED",
        "zone_id": "TZP001",
        "zone_part": "TZP001",
        "zone_type": "PROHIBITED",
        "dataset": "zones",
        "zone_version": "zones:4",
        "cis_version": "zones:4,uspace_airspace:2,restrictions:9",
        "vertical_known": false,
        "limit_not_judged": true,
        "not_judged": [
          "AGL"
        ]
      }
    }
  }
};

/** The ED-318 documents the lab's round-trip vector accepts. */
export const ED318_ACCEPTED: readonly { name: string; document: unknown }[] = [
  {
    "name": "accept-authority-collection",
    "document": {
      "features": [
        {
          "geometry": {
            "coordinates": [
              [
                [
                  44.7,
                  41.65
                ],
                [
                  44.95,
                  41.65
                ],
                [
                  44.95,
                  41.8
                ],
                [
                  44.7,
                  41.8
                ],
                [
                  44.7,
                  41.65
                ]
              ]
            ],
            "layer": {
              "lower": 0,
              "lowerReference": "AGL",
              "uom": "m",
              "upper": 300,
              "upperReference": "WGS84"
            },
            "type": "Polygon"
          },
          "id": "TSU001",
          "properties": {
            "country": "GEO",
            "dataSource": {
              "creationDateTime": "2026-09-01T00:00:00Z",
              "originator": {
                "lang": "en-GB",
                "text": "Test authority"
              },
              "updateDateTime": "2026-09-30T12:00:00Z"
            },
            "extendedProperties": {
              "adjacent": [],
              "airspace_constraints": {
                "max_height_agl_m": 120
              },
              "operational_conditions": {
                "min_ussp_count": 1
              },
              "service_performance": {
                "cis_latency_s": 5,
                "nid_update_hz": 1,
                "ti_update_hz": 1
              },
              "services_required": [
                "NID",
                "GEO",
                "FA",
                "TI"
              ],
              "uas_requirements": {
                "direct_remote_id": true,
                "geo_awareness": true,
                "network_identification": true
              }
            },
            "identifier": "TSU001",
            "message": [
              {
                "lang": "en-GB",
                "text": "U-space airspace: network identification, geo-awareness, flight authorisation and traffic information required"
              }
            ],
            "name": [
              {
                "lang": "en-GB",
                "text": "Tbilisi U-space airspace (test)"
              },
              {
                "lang": "ka-GE",
                "text": "თბილისის U-space საჰაერო სივრცე (ტესტი)"
              }
            ],
            "reason": [
              "AIR_TRAFFIC"
            ],
            "type": "USPACE",
            "variant": "COMMON",
            "zoneAuthority": [
              {
                "contactName": [
                  {
                    "lang": "en-GB",
                    "text": "Duty officer"
                  }
                ],
                "email": "uspace@example.invalid",
                "intervalBefore": "PT1H",
                "name": [
                  {
                    "lang": "en-GB",
                    "text": "Test authority"
                  }
                ],
                "phone": "+995 32 000 0000",
                "purpose": "AUTHORIZATION",
                "service": [
                  {
                    "lang": "en-GB",
                    "text": "U-space designation"
                  }
                ],
                "siteURL": "https://example.invalid/uspace"
              }
            ]
          },
          "type": "Feature"
        },
        {
          "geometry": {
            "coordinates": [
              44.8271,
              41.7151
            ],
            "extent": {
              "radius": 1500,
              "subType": "Circle"
            },
            "layer": {
              "lower": 0,
              "lowerReference": "AGL",
              "uom": "ft",
              "upper": 2500,
              "upperReference": "AMSL"
            },
            "type": "Point"
          },
          "id": 2,
          "properties": {
            "country": "GEO",
            "dataSource": {
              "creationDate": "2026-09-30T08:00:00Z"
            },
            "identifier": "TSD001",
            "limitedApplicability": [
              {
                "endDateTime": "2026-10-08T00:00:00Z",
                "schedule": [
                  {
                    "day": [
                      "ANY"
                    ],
                    "endEvent": "EECT",
                    "startEvent": "BMCT"
                  }
                ],
                "startDateTime": "2026-10-01T00:00:00Z"
              }
            ],
            "message": [
              {
                "lang": "en-GB",
                "text": "Closed from morning to evening civil twilight"
              }
            ],
            "name": [
              {
                "lang": "en-GB",
                "text": "Test event restriction"
              }
            ],
            "otherReasonInfo": [
              {
                "lang": "en-GB",
                "text": "Dynamic restriction from the ANSP"
              }
            ],
            "reason": [
              "DAR",
              "EMERGENCY"
            ],
            "region": 1,
            "regulationExemption": "NO",
            "restrictionConditions": "Emergency services only",
            "type": "PROHIBITED",
            "variant": "CUSTOMIZED",
            "zoneAuthority": [
              {
                "name": [
                  {
                    "lang": "en-GB",
                    "text": "Test ANSP"
                  }
                ],
                "purpose": "NOTIFICATION"
              }
            ]
          },
          "type": "Feature"
        },
        {
          "geometry": {
            "coordinates": [
              [
                [
                  44.8,
                  41.7
                ],
                [
                  44.82,
                  41.7
                ],
                [
                  44.82,
                  41.72
                ],
                [
                  44.8,
                  41.72
                ],
                [
                  44.8,
                  41.7
                ]
              ],
              [
                [
                  44.805,
                  41.705
                ],
                [
                  44.815,
                  41.705
                ],
                [
                  44.815,
                  41.715
                ],
                [
                  44.805,
                  41.715
                ],
                [
                  44.805,
                  41.705
                ]
              ]
            ],
            "layer": {
              "lower": 0,
              "lowerReference": "AGL",
              "uom": "m",
              "upper": 600,
              "upperReference": "WGS84"
            },
            "type": "Polygon"
          },
          "properties": {
            "country": "GEO",
            "extendedProperties": {
              "source": "test"
            },
            "identifier": "TSR001",
            "limitedApplicability": [
              {
                "endDateTime": "2027-01-01T00:00:00+04:00",
                "schedule": [
                  {
                    "day": [
                      "MON",
                      "TUE",
                      "WED",
                      "THU",
                      "FRI"
                    ],
                    "endTime": "18:00:00+04:00",
                    "startTime": "08:00:00+04:00"
                  }
                ],
                "startDateTime": "2026-10-01T00:00:00+04:00"
              }
            ],
            "message": [
              {
                "lang": "en-GB",
                "text": "Authorisation required on weekdays"
              }
            ],
            "name": [
              {
                "lang": "en-GB",
                "text": "Test authorisation zone"
              }
            ],
            "reason": [
              "SENSITIVE",
              "PRIVACY"
            ],
            "restrictionConditions": "Authorisation by the authority",
            "type": "REQ_AUTHORIZATION",
            "variant": "COMMON",
            "zoneAuthority": [
              {
                "email": "zones@example.invalid",
                "intervalBefore": "P2D",
                "name": [
                  {
                    "lang": "en-GB",
                    "text": "Test authority"
                  }
                ],
                "purpose": "AUTHORIZATION",
                "siteURL": "https://example.invalid/zones"
              }
            ]
          },
          "type": "Feature"
        },
        {
          "geometry": {
            "geometries": [
              {
                "coordinates": [
                  [
                    [
                      44.85,
                      41.73
                    ],
                    [
                      44.87,
                      41.73
                    ],
                    [
                      44.87,
                      41.75
                    ],
                    [
                      44.85,
                      41.75
                    ],
                    [
                      44.85,
                      41.73
                    ]
                  ]
                ],
                "layer": {
                  "lower": 0,
                  "lowerReference": "AGL",
                  "uom": "m",
                  "upper": 50,
                  "upperReference": "AGL"
                },
                "type": "Polygon"
              },
              {
                "coordinates": [
                  [
                    [
                      44.855,
                      41.735
                    ],
                    [
                      44.865,
                      41.735
                    ],
                    [
                      44.86,
                      41.745
                    ],
                    [
                      44.855,
                      41.735
                    ]
                  ]
                ],
                "layer": {
                  "lower": 50,
                  "lowerReference": "AGL",
                  "uom": "m",
                  "upper": 150,
                  "upperReference": "AGL"
                },
                "type": "Polygon"
              }
            ],
            "type": "GeometryCollection"
          },
          "properties": {
            "country": "GEO",
            "identifier": "TSC001",
            "limitedApplicability": [
              {
                "schedule": [
                  {
                    "day": [
                      "SAT",
                      "SUN"
                    ],
                    "endTime": "02:00:00Z",
                    "startTime": "22:00:00Z"
                  }
                ]
              }
            ],
            "name": [
              {
                "lang": "en-GB",
                "text": "Test two-layer nature zone"
              }
            ],
            "reason": [
              "NOISE",
              "NATURE"
            ],
            "type": "CONDITIONAL",
            "variant": "COMMON",
            "zoneAuthority": [
              {
                "purpose": "INFORMATION"
              }
            ]
          },
          "type": "Feature"
        },
        {
          "geometry": {
            "coordinates": [
              44.9,
              41.75
            ],
            "extent": {
              "radius": 250.5,
              "subType": "Circle"
            },
            "layer": {
              "lowerReference": "AGL",
              "upperReference": "AMSL"
            },
            "type": "Point"
          },
          "properties": {
            "country": "GEO",
            "identifier": "TSN001",
            "name": [
              {
                "lang": "en-GB",
                "text": "Test information zone"
              }
            ],
            "type": "NO_RESTRICTION",
            "variant": "COMMON",
            "zoneAuthority": [
              {
                "purpose": "INFORMATION"
              }
            ]
          },
          "type": "Feature"
        }
      ],
      "metadata": {
        "description": [
          {
            "lang": "en-GB",
            "text": "Invented zones around Tbilisi for tests; not real restrictions"
          }
        ],
        "issued": "2026-09-30T12:00:00.5Z",
        "otherGeoid": "urn:ogc:def:crs:EPSG::3855",
        "provider": [
          {
            "lang": "en-GB",
            "text": "Test authority"
          },
          {
            "lang": "ka-GE",
            "text": "სატესტო უწყება"
          }
        ],
        "technicalLimitations": [
          {
            "lang": "en-GB",
            "text": "Test data with no legal force"
          }
        ],
        "validFrom": "2026-10-01T00:00:00Z",
        "validTo": "2027-10-01T00:00:00+04:00"
      },
      "name": "Test zones around Tbilisi (ED-318)",
      "type": "FeatureCollection"
    }
  }
];
