import { noHandWrittenApiTypes } from "./noHandWrittenApiTypes.js";
import { ruleTester } from "./ruleTester.testing.js";

const OPENAPI_TS_HEADER = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
`;

ruleTester().run("no-hand-written-api-types", noHandWrittenApiTypes, {
  valid: [
    {
      filename: "web/src/api/generated/openapi.d.ts",
      code: `${OPENAPI_TS_HEADER}export interface paths { "/v1/zones": { get: never } }\nexport interface components { schemas: { Track: { id: string } } }`,
    },
    {
      filename: "web/src/api/generated/openapi.d.ts",
      code: "// @generated by uspace-ui-gen-api from api/openapi.yaml\nexport type Track = { id: string };",
    },
    // Outside the generated directory, a name that is not a component.
    {
      filename: "web/src/adapters/track.ts",
      code: "interface TrackRowProps { id: string }",
      options: [{ componentNames: ["Track"] }],
    },
    // Without the app's component list the rule cannot know the names.
    {
      filename: "web/src/adapters/track.ts",
      code: "interface Track { id: string }",
    },
  ],
  invalid: [
    {
      filename: "web/src/api/generated/extra.ts",
      code: "export interface Track { id: string }",
      errors: [{ messageId: "handWritten" }],
    },
    {
      filename: "web/src/api/generated/extra.ts",
      code: "// helper types\ntype A = string;\ninterface B { a: A }",
      errors: [{ messageId: "handWritten" }, { messageId: "handWritten" }],
    },
    {
      // The marker counts only as the file's first comment at its start.
      filename: "web/src/api/generated/extra.ts",
      code: `export type X = 1;\n${OPENAPI_TS_HEADER}`,
      errors: [{ messageId: "handWritten" }],
    },
    {
      filename: "C:\\web\\src\\api\\generated\\extra.ts",
      code: "export const x = 1;",
      errors: [{ messageId: "handWritten" }],
    },
    {
      filename: "web/src/adapters/track.ts",
      code: "export interface Track { id: string }\nexport type Zone = { id: string };",
      options: [{ componentNames: ["Track", "Zone"] }],
      errors: [
        { messageId: "shadowed", data: { name: "Track" } },
        { messageId: "shadowed", data: { name: "Zone" } },
      ],
    },
  ],
});
