import type { Rule } from "eslint";

import { posixFilename } from "./sources.js";

// Spec 00 §6.2 and CLAUDE.md rule 8: API types are generated from each
// system's api/openapi.yaml, never hand-written.
export const GENERATED_DIR = /(?:^|\/)src\/api\/generated\//;

// Text the first comment of a generated file carries: the header
// openapi-typescript writes, and the one uspace-ui-gen-api (WP-4) adds.
export const GENERATED_MARKERS: readonly string[] = [
  "This file was auto-generated by openapi-typescript",
  "@generated by uspace-ui-gen-api",
];

interface Options {
  componentNames?: string[];
}

interface NamedDeclaration {
  id: { name: string };
}

export const noHandWrittenApiTypes: Rule.RuleModule = {
  meta: {
    type: "problem",
    docs: {
      description:
        "Only generated files live in src/api/generated/; schema component names are not redeclared by hand (00 §6.2).",
    },
    schema: [
      {
        type: "object",
        properties: {
          componentNames: { type: "array", items: { type: "string" } },
        },
        additionalProperties: false,
      },
    ],
    messages: {
      handWritten:
        "Hand-written file in src/api/generated/. Generate it with uspace-ui-gen-api from the system's api/openapi.yaml.",
      shadowed:
        "'{{name}}' is a schema component of the system's API. Use the generated type, never a hand-written copy.",
    },
  },
  create(context) {
    const filename = posixFilename(context);
    const options = (context.options[0] ?? {}) as Options;

    if (GENERATED_DIR.test(filename)) {
      const head = context.sourceCode.getAllComments()[0];
      const generated =
        head?.range?.[0] === 0 &&
        GENERATED_MARKERS.some((m) => head.value.includes(m));
      if (generated) return {};
      let reported = false;
      const report = (node: Rule.Node): void => {
        reported = true;
        context.report({ node, messageId: "handWritten" });
      };
      return {
        TSInterfaceDeclaration: report,
        TSTypeAliasDeclaration: report,
        "Program:exit"(node) {
          if (!reported) context.report({ node, messageId: "handWritten" });
        },
      };
    }

    const names = new Set(options.componentNames ?? []);
    if (names.size === 0) return {};
    const check = (node: Rule.Node): void => {
      const name = (node as unknown as NamedDeclaration).id.name;
      if (names.has(name))
        context.report({ node, messageId: "shadowed", data: { name } });
    };
    return { TSInterfaceDeclaration: check, TSTypeAliasDeclaration: check };
  },
};
