// Story-only sample text in both languages (the kit's catalogues come with
// WP-2). Nothing here is a user-facing string of the kit itself.
export type StoryLang = "en" | "ka";

export const TEXTS = {
  en: {
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    delete: "Delete",
    outline: "Outline",
    secondary: "Secondary",
    ghost: "Ghost",
    link: "Link",
    badge: "Badge",
    cardTitle: "Receiver TEST-RX-01",
    cardDescription: "Last status 12 s ago (UTC)",
    cardBody: "Placeholder content for the card body.",
    dialogTitle: "Acknowledge the alert",
    dialogDescription: "The acknowledgement is recorded with your name.",
    alertTitle: "Disable the source?",
    alertDescription: "The source stops feeding the picture until enabled.",
    sheetTitle: "Layers",
    sheetDescription: "Choose what the map shows.",
    tabOne: "Overview",
    tabTwo: "History",
    tabOneBody: "Overview of the selected item.",
    tabTwoBody: "History of the selected item.",
    tooltip: "Shown on hover and focus",
    tooltipTrigger: "Hover me",
    popoverTrigger: "Details",
    popoverBody: "Popover content.",
    menuTrigger: "Actions",
    menuLabel: "Track",
    menuItemOne: "Show details",
    menuItemTwo: "Copy identifier",
    menuChecked: "Follow on map",
    commandPlaceholder: "Search…",
    commandEmpty: "No results.",
    commandGroup: "Views",
    commandItemOne: "Map",
    commandItemTwo: "Alerts",
    selectLabel: "Language",
    selectPlaceholder: "Choose a language",
    selectEn: "English",
    selectKa: "Georgian",
    checkbox: "Show stale tracks",
    radioLabel: "Altitude reference",
    radioAmsl: "m AMSL",
    radioAgl: "m AGL",
    switchLabel: "Sound for critical alerts",
    inputLabel: "Serial number",
    inputPlaceholder: "TEST-0001",
    textareaLabel: "Reason",
    textareaPlaceholder: "Why is this change made?",
    separatorTop: "Above the separator",
    separatorBottom: "Below the separator",
    scrollLabel: "Event log",
    scrollRow: "Event",
    tableCaption: "Sources",
    tableName: "Name",
    tableState: "State",
    tableAge: "Age (s)",
    tableLive: "live",
    tableStale: "stale",
    skeletonLabel: "Loading",
    toastTrigger: "Show a toast",
    toastText: "Saved",
    crumbHome: "Home",
    crumbZones: "Zones",
    crumbCurrent: "TEST-ZONE-01",
    pageNav: "Pages",
    pagePrevious: "Previous page",
    pageNext: "Next page",
    page: "Page",
    collapsibleTrigger: "More details",
    collapsibleBody: "Collapsible content.",
    kbd: "Press",
    kbdTail: "to close",
    statLabel: "Height",
    statUnknownLabel: "Speed",
    statUnit: "m AGL",
    emptyTitle: "No alerts",
    emptyDescription: "No alert is open in this area.",
    codeLead: "The variable is",
  },
  ka: {
    save: "შენახვა",
    cancel: "გაუქმება",
    close: "დახურვა",
    delete: "წაშლა",
    outline: "კონტური",
    secondary: "მეორადი",
    ghost: "გამჭვირვალე",
    link: "ბმული",
    badge: "ნიშანი",
    cardTitle: "მიმღები TEST-RX-01",
    cardDescription: "ბოლო სტატუსი 12 წმ-ის წინ (UTC)",
    cardBody: "ბარათის შიგთავსის ნიმუში.",
    dialogTitle: "განგაშის დადასტურება",
    dialogDescription: "დადასტურება ჩაიწერება თქვენი სახელით.",
    alertTitle: "გამოირთოს წყარო?",
    alertDescription: "წყარო აღარ მიაწვდის მონაცემებს ჩართვამდე.",
    sheetTitle: "ფენები",
    sheetDescription: "აირჩიეთ, რას აჩვენებს რუკა.",
    tabOne: "მიმოხილვა",
    tabTwo: "ისტორია",
    tabOneBody: "არჩეული ელემენტის მიმოხილვა.",
    tabTwoBody: "არჩეული ელემენტის ისტორია.",
    tooltip: "ჩანს მიტანისას და ფოკუსისას",
    tooltipTrigger: "მიიტანეთ კურსორი",
    popoverTrigger: "დეტალები",
    popoverBody: "ამომხტარი ფანჯრის შიგთავსი.",
    menuTrigger: "მოქმედებები",
    menuLabel: "ტრეკი",
    menuItemOne: "დეტალების ჩვენება",
    menuItemTwo: "იდენტიფიკატორის კოპირება",
    menuChecked: "რუკაზე თვალყურის დევნება",
    commandPlaceholder: "ძიება…",
    commandEmpty: "შედეგი არ არის.",
    commandGroup: "ხედები",
    commandItemOne: "რუკა",
    commandItemTwo: "განგაშები",
    selectLabel: "ენა",
    selectPlaceholder: "აირჩიეთ ენა",
    selectEn: "ინგლისური",
    selectKa: "ქართული",
    checkbox: "მოძველებული ტრეკების ჩვენება",
    radioLabel: "სიმაღლის ათვლა",
    radioAmsl: "მ ზღვის დონიდან (AMSL)",
    radioAgl: "მ მიწიდან (AGL)",
    switchLabel: "ხმა კრიტიკული განგაშისთვის",
    inputLabel: "სერიული ნომერი",
    inputPlaceholder: "TEST-0001",
    textareaLabel: "მიზეზი",
    textareaPlaceholder: "რატომ ხდება ეს ცვლილება?",
    separatorTop: "გამყოფის ზემოთ",
    separatorBottom: "გამყოფის ქვემოთ",
    scrollLabel: "მოვლენების ჟურნალი",
    scrollRow: "მოვლენა",
    tableCaption: "წყაროები",
    tableName: "სახელი",
    tableState: "მდგომარეობა",
    tableAge: "ასაკი (წმ)",
    tableLive: "ცოცხალი",
    tableStale: "მოძველებული",
    skeletonLabel: "იტვირთება",
    toastTrigger: "შეტყობინების ჩვენება",
    toastText: "შენახულია",
    crumbHome: "მთავარი",
    crumbZones: "ზონები",
    crumbCurrent: "TEST-ZONE-01",
    pageNav: "გვერდები",
    pagePrevious: "წინა გვერდი",
    pageNext: "შემდეგი გვერდი",
    page: "გვერდი",
    collapsibleTrigger: "მეტი დეტალი",
    collapsibleBody: "ჩაკეცვადი შიგთავსი.",
    kbd: "დააჭირეთ",
    kbdTail: "დასახურად",
    statLabel: "სიმაღლე",
    statUnknownLabel: "სიჩქარე",
    statUnit: "მ AGL",
    emptyTitle: "განგაში არ არის",
    emptyDescription: "ამ არეალში ღია განგაში არ არის.",
    codeLead: "ცვლადია",
  },
} as const satisfies Record<StoryLang, Record<string, string>>;

export type Texts = (typeof TEXTS)[StoryLang];

export function texts(globals: Record<string, unknown>): Texts {
  return globals["lang"] === "ka" ? TEXTS.ka : TEXTS.en;
}
