// The uspace-ui-gen-api bin (WP-4, PLAN §14 Q14): the header, --check on a
// current and on a hand-edited output, and the usage and input errors.
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Linter } from "eslint";
import tseslint from "typescript-eslint";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { plugin } from "../../eslint/index.js";
import { genApi } from "./run.testing.js";

const FIXTURE = "src/api/test/fixture.yaml";
const pkg = JSON.parse(readFileSync("package.json", "utf8")) as {
  version: string;
  dependencies: Record<string, string>;
};

let dir = "";

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), "gen-api-"));
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

function lint(code: string): string[] {
  const linter = new Linter({ configType: "flat" });
  return linter
    .verify(
      code,
      [
        {
          files: ["**/*.ts"],
          languageOptions: { parser: tseslint.parser },
          plugins: { "uspace-ui": plugin },
          rules: { "uspace-ui/no-hand-written-api-types": "error" },
        },
      ],
      "web/src/api/generated/openapi.d.ts",
    )
    .map((m) => m.message);
}

function generated(): string {
  const out = join(dir, "openapi.d.ts");
  const r = genApi(FIXTURE, out);
  expect(r.stderr).toBe("");
  expect(r.status).toBe(0);
  return out;
}

describe("uspace-ui-gen-api", () => {
  it("writes the header with its version, the generator's and the input's sha256", () => {
    const text = readFileSync(generated(), "utf8");
    const sha256 = createHash("sha256")
      .update(readFileSync(FIXTURE))
      .digest("hex");
    const generator = pkg.dependencies["openapi-typescript"] ?? "";
    expect(text.split("\n")[0]).toBe(
      `// @generated by uspace-ui-gen-api ${pkg.version} (openapi-typescript ${generator}) from ${sha256}; do not edit`,
    );
    expect(text).toContain("export interface paths {");
    expect(text).toContain('"/v1/zones/{identifier}/notes"');
  });

  it("writes output the no-hand-written-api-types rule accepts, and refuses it stripped", () => {
    const text = readFileSync(generated(), "utf8");
    expect(lint(text)).toEqual([]);
    const stripped = text.slice(text.indexOf("export interface paths"));
    expect(lint(stripped).length).toBeGreaterThan(0);
  });

  it("--check passes on a current output", () => {
    const out = generated();
    const r = genApi(FIXTURE, out, "--check");
    expect(r.status).toBe(0);
    expect(r.stdout).toContain("is current");
  });

  it("--check fails on a hand-edited copy and leaves it as it was", () => {
    const out = generated();
    const edited = readFileSync(out, "utf8").replace(
      "cis_version: number;",
      "cis_version: string;",
    );
    expect(edited).not.toBe(readFileSync(out, "utf8"));
    writeFileSync(out, edited);
    const r = genApi(FIXTURE, out, "--check");
    expect(r.status).toBe(1);
    expect(r.stderr).toContain("is not what");
    expect(readFileSync(out, "utf8")).toBe(edited);
  });

  it("--check fails when the output is missing", () => {
    const r = genApi(FIXTURE, join(dir, "absent.d.ts"), "--check");
    expect(r.status).toBe(1);
    expect(r.stderr).toContain("is missing");
  });

  it.each([[[]], [[FIXTURE]], [[FIXTURE, "a", "b"]], [[FIXTURE, "--out"]]])(
    "exits 2 with the usage on %j",
    (args) => {
      const r = genApi(...args);
      expect(r.status).toBe(2);
      expect(r.stderr).toContain("usage: uspace-ui-gen-api");
    },
  );

  it("exits 2 on an absent input", () => {
    const r = genApi(join(dir, "absent.yaml"), join(dir, "out.d.ts"));
    expect(r.status).toBe(2);
    expect(r.stderr).toContain("does not exist");
  });

  it("exits 2 on an input that is not OpenAPI", () => {
    const bad = join(dir, "bad.yaml");
    writeFileSync(bad, "not: [an, openapi, file\n");
    const r = genApi(bad, join(dir, "out.d.ts"));
    expect(r.status).toBe(2);
    expect(r.stderr).toContain("cannot generate");
  });
});
