// Writes or checks docs/api/uspace-ui.api.md, the API report of every
// entry point (PLAN §6.3, §12). api-extractor reads one entry, so this
// writes a temporary one that re-exports each `exports` key of
// package.json as a namespace (`./auth/server` -> `auth_server`), then
// runs api-extractor on it.
//
//   node scripts/api-report.mjs          check: fails if the report is stale
//   node scripts/api-report.mjs --local  update the committed report
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { Extractor, ExtractorConfig } from "@microsoft/api-extractor";

const root = process.cwd();
const local = process.argv.includes("--local");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

const entryDir = join(root, ".cache", "api");
mkdirSync(entryDir, { recursive: true });

const lines = ["// Generated by scripts/api-report.mjs; not committed."];
for (const [key, target] of Object.entries(pkg.exports)) {
  if (typeof target !== "object" || !target.types) continue;
  const types = join(root, target.types);
  if (!existsSync(types)) {
    console.error(
      `api-report: ${target.types} is missing; run pnpm build first`,
    );
    process.exit(1);
  }
  const ns = key.slice(2).replace(/[^A-Za-z0-9]/g, "_");
  const spec = relative(entryDir, types)
    .replace(/\\/g, "/")
    .replace(/\.d\.ts$/, ".js");
  lines.push(`export * as ${ns} from "${spec}";`);
}
writeFileSync(join(entryDir, "entry.d.ts"), `${lines.join("\n")}\n`);

const config = ExtractorConfig.loadFileAndPrepare(
  join(root, "scripts", "api-extractor.json"),
);
const result = Extractor.invoke(config, {
  localBuild: local,
  showVerboseMessages: false,
});

if (!result.succeeded) {
  console.error(
    local
      ? `api-report: api-extractor failed (${result.errorCount} errors, ${result.warningCount} warnings)`
      : "api-report: docs/api/uspace-ui.api.md is stale or the API has errors; run pnpm api-report and commit the result",
  );
  process.exit(1);
}
console.log(
  result.apiReportChanged
    ? "api-report: docs/api/uspace-ui.api.md updated"
    : "api-report: docs/api/uspace-ui.api.md is up to date",
);
