// `@rootxkit/uspace-ui/symbology` (docs/PLAN.md §3.8): pure functions from
// enumerations to visual values and MapLibre expressions. No React, no map.
// WP-6 adds the zone and restriction part; WP-7 adds the track part;
// WP-12 adds the manned and intent parts.
export { AGE_BUCKET_KEYS, ageBucket, ageOpacity, ageToken } from "./age.js";
export {
  DSS_STATES,
  INTENT_ACTIVE_EXTRA_FILL,
  INTENT_ACTIVE_EXTRA_WIDTH_PX,
  INTENT_PATTERN_TILE_PX,
  INTENT_PEER_PATTERN_ID,
  INTENT_SELECTED_EXTRA_WIDTH_PX,
  INTENT_STATE_KEYS,
  INTENT_STATE_KEYS_ORDER,
  intentLook,
  intentPeerPatternImage,
  intentStateDrawn,
  intentStateFilter,
  isDssState,
  type DssState,
  type IntentFeatureProperties,
  type IntentKey,
  type IntentLook,
  type IntentStateKey,
} from "./intent.js";
export {
  MANNED_COLOUR_TOKENS,
  MANNED_ICON_IDS,
  MANNED_ICON_PX,
  MANNED_SOURCE_CLASS_KEYS,
  mannedFill,
  mannedIconDistance,
  mannedIconId,
  mannedIconParts,
  mannedIconSdf,
  mannedStyle,
  mannedToken,
  mannedTrustDrawn,
  type MannedColours,
  type MannedFeatureProperties,
  type MannedFill,
  type MannedStyle,
  type MannedTrack,
} from "./manned.js";
export {
  IDENT_BASIS_KEYS,
  IDENT_ORDER,
  IDENT_REASON_KEYS,
  IDENT_STATUS_HINT_KEYS,
  IDENT_STATUS_KEYS,
  identDrawn,
  identHintKey,
  identMark,
  identOrder,
  identToken,
  needsAttention,
  type IdentHint,
  type IdentKey,
} from "./ident.js";
export {
  RESTRICTION_LINE_KEYS,
  RESTRICTION_STATE_KEYS,
  restrictionLine,
  restrictionLineFilter,
  restrictionStateToken,
  type RestrictionLine,
  type RestrictionLineKey,
} from "./restriction.js";
export {
  DIMMED_RESTRICTION_STATES,
  PATTERN_TILE_PX,
  PATTERNED_ZONE_TYPES,
  SELECTED_EXTRA_WIDTH_PX,
  ZONE_DIMMED_OPACITY,
  ZONE_LEGEND_ORDER,
  ZONE_PATTERN_KEYS,
  ZONE_TYPE_KEYS,
  parseHexColour,
  zoneDimExpression,
  zoneLineWidthPx,
  zoneOpacity,
  zoneOrder,
  zonePattern,
  zonePatternFillOpacity,
  zonePatternImage,
  zonePatternImageId,
  zoneStyle,
  zoneToken,
  type PatternImage,
  type Rgb,
  type ZoneColours,
  type ZoneFeatureProperties,
  type ZonePattern,
  type ZoneStyle,
} from "./zone.js";
export {
  SEVERITY_HINT_KEYS,
  SEVERITY_KEYS,
  SEVERITY_ORDER,
  severityGlyph,
  severityOrder,
  severityToken,
  type SeverityGlyph,
} from "./severity.js";
export {
  TRACK_COLOUR_TOKENS,
  TRACK_ICON_IDS,
  TRUST_KEYS,
  TRUST_MEANING_KEYS,
  TRUST_ORDER,
  ageOpacityExpression,
  trackIconId,
  trackStyle,
  trustOrder,
  trustToken,
  type TrackColours,
  type TrackFeatureProperties,
  type TrackStyle,
  type TrailFeatureProperties,
} from "./track.js";
export {
  TRACK_ICON_PIXEL_RATIO,
  TRACK_ICON_PX,
  trackIconDistance,
  trackIconParts,
  trackIconSdf,
  trackIconSvg,
  trustFill,
  trustShape,
  type IconPart,
  type IconPoint,
  type Shape,
  type ShapeFill,
} from "./trackIcon.js";
